# Setup
title:               Hi :)
tagline:             '.'
description:         '.'
url:                 'http://hyuunnn.github.io'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Hyun Yi
  #url:               https://twitter.com/mdo
  #email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
